spring.application.name=carbonhub

# DB
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

#JPA
spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}

# JWT
security.jwt.secret-key=${JWT_SECRET}
security.jwt.expiration-time=${JWT_EXPIRATION}

# Google OpenID Connect
security.google.client-id=${GOOGLE_CLIENT_ID:}
security.google.jwks-uri=https://www.googleapis.com/oauth2/v3/certs
security.google.timeout-ms=10000

#Spring AI
spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.options.model=gemini-3.5-flash
